defaults: &job-defaults
  docker:
    - image: circleci/node:8.12-stretch-browsers
      environment:
        - TZ: "/usr/share/zoneinfo/America/Los_Angeles"
        - CHROME_BIN: "/usr/bin/google-chrome"

version: 2
jobs:
  install:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package-lock.json" }}
            - v1-dependency-cache-
      - run: git submodule update --init --remote --merge
      - run:
          name: npm install
          command: npm ci
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - libs/deployment_scripts
  build:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Set version
          command: node libs/deployment_scripts/src/versioning.js
      - run:
          name: Build Angular app
          command: ./libs/deployment_scripts/src/build-angular.sh
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths:
            - dist
  aws_sts:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Make Access Credentials directory
          command: mkdir -p deployment_credentials/
      - run:
          name: Create Credentials
          command: node ./libs/deployment_scripts/src/sts-assume-role.js $CIRCLE_BRANCH >> deployment_credentials/stscredentials
      - persist_to_workspace:
          root: .
          paths:
            - deployment_credentials
      - run:
          name: set credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
  deploy_s3:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Deploy App to s3
          command: node libs/deployment_scripts/src/deploy-s3.js deployment/deploy-config.json
  deploy_cloudfront:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Add/Update CloudFront Distribution
          command: node libs/deployment_scripts/src/deploy-cloudfront.js deployment/deploy-config.json
  e2e_local_smoke:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
      - run:
          name: Update webdriver
          command: npm run pree2e
      - run:
          name: Run local server
          command: npm run start
          background: true
      - run:
          name: Wait for server to start
          command: sleep 60
      - run:
          name: Run local smoke e2e
          command: npm run e2e.local -- --suite smoke
          no_output_timeout: 20m
  e2e_smoke_deploy_report:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
      - run:
          name: Update webdriver
          command: npm run pree2e
      - run:
          name: Run e2e smoke
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              npm run e2e.dev -- --suite smoke
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              npm run e2e.stage -- --suite smoke
            fi
          no_output_timeout: 20m
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
          when: always
      - run:
          name: Deploy Report to s3
          command: node libs/deployment_scripts/src/deploy-report.js deployment/deploy-config.json
          when: always

workflows:
  version: 2
  build_deploy_test_and_merge:
    jobs:
      - install
      - build:
          requires:
            - install
      - aws_sts:
          requires:
            - install
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - deploy_s3:
          requires:
            - build
            - aws_sts
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - deploy_cloudfront:
          requires:
            - deploy_s3
      - e2e_local_smoke:
          requires:
            - install
          filters:
            branches:
              ignore:
                - development
                - staging
                - production
                - priority
      - e2e_smoke_deploy_report:
          requires:
            - deploy_cloudfront
          filters:
            branches:
              only:
                - development
                - staging
